function fish(name, habitat, prize, abundance, note, sizeRule, takeNote) {
  return { name, habitat, prize, abundance, note, sizeRule, takeNote };
}

const fishLists = {
  "lower-keys": [
    fish("Yellowtail snapper", "Mid-water over reef", 78, 95, "#1 Keys table fish", "12 in total length minimum; 10/day.", "Legal outside FKNMS no-take zones. Confirm the current snapper aggregate before taking."),
    fish("Hogfish", "Sandy reef channels", 92, 60, "#1 Keys spear trophy", "16 in fork length minimum; 1/harvester/day; May 1-Oct 31 only.", "Closed Nov 1-Apr 30 in Atlantic/Monroe waters."),
    fish("Mutton snapper", "Reef edges 40-120 ft", 90, 55, "prime spear target", "18 in total length minimum; 5/day.", "Counts toward the snapper aggregate."),
    fish("Gray snapper", "Patch reefs / structure", 65, 90, "reliable food fish", "10 in total length minimum; 5/day.", "Often called mangrove snapper."),
    fish("Black grouper", "Spur-and-groove ledges", 95, 35, "top grouper trophy", "24 in total length minimum; 1/harvester/day; 2/vessel max with black/gag.", "Closed Jan 1-Apr 30 in Monroe County."),
    fish("Red grouper", "Hard-bottom holes", 82, 50, "classic Keys grouper", "20 in total length minimum.", "Monroe grouper closure applies Jan 1-Apr 30."),
    fish("Bluestriped grunt", "Under ledges", 25, 92, "ubiquitous, light table", "Verify current grunt/snapper family rules.", "Good ID matters before retaining."),
    fish("Blue tang", "Reef grazers", 0, 90, "marine life species", "No spearfishing / no take for this use case.", "Treat as a look-only reef fish."),
    fish("Stoplight parrotfish", "Reef herbivore", 0, 85, "no-take in FKNMS", "No take.", "Parrotfish are not a spear target here."),
    fish("Great barracuda", "Mid-water", 28, 70, "ciguatera risk", "Verify current FWC guidance.", "Usually not worth targeting for table fare."),
    fish("African pompano", "Deeper reef / wrecks", 90, 18, "rare deep-reef prize", "Verify current FWC guidance before taking.", "More realistic on deeper wreck/reef dives."),
    fish("Lionfish", "Reef crevices", 70, 55, "invasive, spear encouraged", "No minimum size or bag limit.", "Use care handling spines.")
  ],
  "deerfield-beach": [
    fish("Sheepshead", "Piling barnacle-grazers", 72, 92, "#1 pier table fish", "12 in total length minimum; 8/day.", "No spearfishing within 100 yards of the pier or public swimming beach."),
    fish("Mangrove snapper", "Piling shadows", 65, 88, "solid food fish", "10 in total length minimum; 5/day.", "Offshore reef tract only for spearing."),
    fish("Snook", "Piling ambush", 95, 70, "NO-SPEAR statewide", "Do not spear.", "Hook-and-line rules are separate; no-spear statewide."),
    fish("Tarpon", "Mid-water around pier", 100, 55, "NO-SPEAR statewide", "Do not spear.", "Large tarpon also require special handling/tag rules for harvest."),
    fish("Great barracuda", "Mid-water apex", 30, 78, "low food value", "Verify current FWC guidance.", "Not a primary table target."),
    fish("Crevalle jack", "Schooling mid-water", 45, 82, "strong fighter", "Verify current FWC guidance.", "Oily flesh; not a high table target."),
    fish("Lookdown", "Schools near pilings", 25, 75, "iconic cam regular", "Not a practical spear target here.", "Pier buffer makes this look-only at the cam."),
    fish("Porkfish", "Reef-associated schools", 22, 70, "light table", "Verify current ornamental/reef fish rules.", "Do not treat cam sightings as legal pier targets."),
    fish("Gray triggerfish", "Piling structure", 70, 50, "excellent table", "12 in fork length minimum; 1/day Atlantic.", "Offshore reef tract only for spearing."),
    fish("Spanish / cero mackerel", "Pelagic passers", 65, 45, "prime food fish", "Spanish: 12 in fork length minimum; 15/day.", "King mackerel has separate 24 in fork length guidance."),
    fish("Cobia", "Piling shadows", 88, 12, "trophy visitor", "36 in fork length minimum; 1/person; 2/vessel.", "Do not spear at the pier; offshore only."),
    fish("Sergeant major", "Damselfish on pilings", 5, 90, "ornamental, no-spear", "Do not spear.", "Treat as a viewing species.")
  ],
  "utopia-sandy-channel": [
    fish("Southern stingray", "Sand pockets", 0, 88, "signature sandy-channel species", "Viewing only.", "Roatan Marine Park / BINMP is no-take at this site."),
    fish("Yellow stingray", "Sand patches", 0, 80, "small and common", "Viewing only.", "No spearfishing at this site."),
    fish("Bar jack", "Mid-water over sand", 50, 90, "often follows rays", "Viewing only.", "Prize is reference-only here; no take is legal."),
    fish("Sand diver", "Sand ambush predator", 5, 75, "bottom cam regular", "Viewing only.", "No take at this site."),
    fish("Peacock flounder", "Sand camouflage", 35, 60, "color-changing flatfish", "Viewing only.", "No take at this site."),
    fish("Goatfish", "Sand foraging schools", 30, 78, "bottom-rooting schools", "Viewing only.", "No take at this site."),
    fish("Hogfish", "Sand-reef interface", 92, 45, "prized elsewhere", "Viewing only.", "No take at this site."),
    fish("Yellowhead jawfish", "Sand burrows", 10, 65, "classic channel sighting", "Viewing only.", "No take at this site."),
    fish("Spotted eagle ray", "Crossing sand channels", 0, 30, "highlight encounter", "Viewing only.", "Protected/look-only encounter."),
    fish("Nassau grouper", "Sand-reef edges", 100, 18, "no-take everywhere", "Viewing only.", "Do not target."),
    fish("Spotted scorpionfish", "Sand / rubble", 15, 50, "master camouflage", "Viewing only.", "No take at this site."),
    fish("Caribbean reef squid", "Mid-water over sand", 30, 40, "cephalopod regular", "Viewing only.", "No take at this site.")
  ],
  "utopia-reef-cam": [
    fish("Blue tang", "Mid-water grazers", 0, 95, "iconic reef fish", "Viewing only.", "Roatan Marine Park / BINMP is no-take at this site."),
    fish("Stoplight parrotfish", "Reef herbivore", 0, 92, "key grazer, no-take", "Viewing only.", "Parrotfish are protected here."),
    fish("Bluehead wrasse", "Reef cleaners", 0, 90, "common reef cruiser", "Viewing only.", "No take at this site."),
    fish("Sergeant major", "Reef tops", 0, 88, "territorial damselfish", "Viewing only.", "No take at this site."),
    fish("French grunt", "Under ledges", 25, 85, "classic Caribbean school", "Viewing only.", "Prize is reference-only here."),
    fish("Foureye butterflyfish", "Reef pairs", 0, 80, "charismatic regular", "Viewing only.", "No take at this site."),
    fish("Yellowtail snapper", "Mid-water over reef", 78, 78, "target elsewhere", "Viewing only.", "No take at this site."),
    fish("Queen / French angelfish", "Reef structure", 0, 60, "trophy viewing fish", "Viewing only.", "Marine-life style species; no take here."),
    fish("Hogfish", "Sandy reef edges", 92, 45, "trophy elsewhere", "Viewing only.", "No take at this site."),
    fish("Nassau grouper", "Reef holes", 100, 25, "no-take everywhere", "Viewing only.", "Do not target."),
    fish("Caribbean reef shark", "Off the wall", 75, 15, "charismatic megafauna", "Viewing only.", "Look-only encounter."),
    fish("Lionfish", "Reef ledges", 60, 35, "only permit exception", "RMP permit/workshop required.", "Lionfish may only be culled with RMP approval and correct gear.")
  ],
  "catalina-wrigley": [
    fish("Blacksmith", "Mid-water over reef", 12, 95, "dominant schooler", "Viewing only.", "Blue Cavern Onshore SMCA is no-take."),
    fish("Senorita", "Reef cleaning stations", 8, 92, "always present", "Viewing only.", "No take at this site."),
    fish("Garibaldi", "Reef nests", 0, 90, "prohibited statewide", "Do not take.", "Garibaldi are protected statewide."),
    fish("Kelp bass", "Kelp edge", 0, 85, "Wrigley study species", "Viewing only.", "No take inside this SMCA."),
    fish("Opaleye", "Shallow reef / surfgrass", 0, 80, "large schools", "Viewing only.", "No take at this site."),
    fish("California sheephead", "Reef boulders", 0, 75, "large males common", "Viewing only.", "No take inside this SMCA."),
    fish("Halfmoon", "Kelp canopy", 0, 70, "mid-water schools", "Viewing only.", "No take at this site."),
    fish("Black perch", "Reef-sand edge", 0, 65, "surfperch family", "Viewing only.", "No take at this site."),
    fish("Giant sea bass", "Reef / kelp", 100, 25, "iconic protected giant", "Do not take.", "Protected statewide."),
    fish("Bat ray", "Sand patches", 0, 35, "regular cove sighting", "Viewing only.", "No take at this site."),
    fish("Horn shark", "Reef ledges", 0, 40, "nocturnal regular", "Viewing only.", "No take at this site."),
    fish("Giant kelpfish", "Kelp canopy", 0, 30, "cryptic in kelp", "Viewing only.", "No take at this site.")
  ],
  "anacapa-ocean": [
    fish("Blacksmith", "Kelp mid-water", 12, 95, "dominant schooler", "Viewing / zoning dependent.", "Anacapa rules depend heavily on which side and MPA zone you are in."),
    fish("Senorita", "Reef cleaners", 8, 90, "second-most-abundant", "Viewing / zoning dependent.", "Check exact zone before any take."),
    fish("Kelp bass", "Kelp / reef", 62, 85, "legal south-side target", "14 in total length minimum in open coast.", "Not legal inside no-take zones."),
    fish("Garibaldi", "Reef", 0, 85, "prohibited statewide", "Do not take.", "Protected statewide."),
    fish("California sheephead", "Reef", 70, 78, "legal south-side target", "12 in total length minimum in open coast.", "Check zone and current CDFW rules."),
    fish("Opaleye", "Shallow reef", 38, 72, "schooling reef fish", "Verify current open-coast rules.", "Not legal inside no-take zones."),
    fish("Halfmoon", "Kelp canopy", 35, 65, "mid-water schools", "Verify current open-coast rules.", "Not legal inside no-take zones."),
    fish("White seabass", "Outer kelp", 96, 22, "south-side trophy only", "28 in total length minimum in open coast.", "Not on the Anacapa SMCA pelagic-finfish take list."),
    fish("Yellowtail", "Open water / kelp edge", 92, 28, "pelagic target", "24 in fork length minimum.", "Legal in the SMCA as pelagic finfish where take is allowed."),
    fish("California barracuda", "Kelp edge", 55, 45, "pelagic target", "28 in fork length minimum.", "Legal in the SMCA as pelagic finfish where take is allowed."),
    fish("Giant sea bass", "Kelp / reef", 100, 18, "prohibited statewide", "Do not take.", "Protected statewide."),
    fish("Bat ray / leopard shark", "Sand-reef edge", 15, 30, "classic island sighting", "Verify current rules.", "Often better treated as viewing wildlife.")
  ],
  "coral-city": [
    fish("Yellowtail parrotfish", "Boulder reef", 0, 92, "signature regular", "Viewing only.", "PortMiami security zone + aquatic preserve; no diving, no spearfishing, no fishing access."),
    fish("Mangrove snapper", "Boulder shadows", 65, 90, "always present", "Viewing only.", "No recreational take at this camera site."),
    fish("Sergeant major", "Riprap tops", 0, 88, "territorial schools", "Viewing only.", "No take at this site."),
    fish("Great barracuda", "Mid-water", 30, 78, "resident apex", "Viewing only.", "No take at this site."),
    fish("Blue tang", "Boulder grazers", 0, 75, "grazing schools", "Viewing only.", "No take at this site."),
    fish("Stoplight / rainbow parrotfish", "Boulder grazers", 0, 72, "multiple parrotfish species", "Viewing only.", "Parrotfish are look-only here."),
    fish("Sheepshead", "Pilings / structure", 72, 65, "barnacle eater", "Viewing only.", "No recreational take at the camera site."),
    fish("French / queen angelfish", "Reef pairs", 0, 55, "charismatic pair", "Viewing only.", "Marine-life style species; no take here."),
    fish("Hogfish", "Sand-boulder interface", 92, 40, "cam favorite", "Viewing only.", "No take at this site."),
    fish("Lemon shark", "Channel", 0, 35, "named regular", "Viewing only.", "Protected/look-only encounter."),
    fish("Atlantic spadefish", "Mid-water schools", 35, 45, "seasonal", "Viewing only.", "No take at this site."),
    fish("West Indian manatee", "Channel passers", 0, 25, "ESA-protected", "Do not approach or disturb.", "Protected species.")
  ],
  "pompano-pier": [
    fish("Sheepshead", "Piling barnacles", 72, 92, "#1 pier table fish", "12 in total length minimum; 8/day.", "No spearfishing within 100 yards of the pier or public beach."),
    fish("Mangrove snapper", "Pilings / structure", 65, 88, "constant structure fish", "10 in total length minimum; 5/day.", "Offshore reef tract only for spearing."),
    fish("Snook", "Pier shadow ambush", 95, 75, "NO-SPEAR statewide", "Do not spear.", "Hook-and-line rules are separate."),
    fish("Florida pompano", "Surf line", 90, 60, "NO-SPEAR", "Do not spear.", "Pompano spearing is prohibited."),
    fish("Permit", "Pier / inlet wash", 90, 30, "NO-SPEAR", "Do not spear.", "Permit are on the no-spear list."),
    fish("Great barracuda", "Mid-water", 30, 78, "resident apex", "Verify current FWC guidance.", "Usually not a table target."),
    fish("Crevalle jack", "Inlet schools", 45, 80, "hard fighter", "Verify current FWC guidance.", "Oily flesh; lower table value."),
    fish("Tarpon", "Pier corners", 100, 45, "NO-SPEAR statewide", "Do not spear.", "Large tarpon require special tag rules for harvest."),
    fish("Yellowtail snapper", "Offshore reef tract", 78, 70, "#1 reef table fish", "12 in total length minimum; 10/day.", "Legal offshore, not in pier buffer."),
    fish("Mutton snapper", "Outer reef ledges", 90, 35, "prime spear trophy", "18 in total length minimum; 5/day.", "Counts toward snapper aggregate."),
    fish("King / Spanish mackerel", "Inlet passers", 65, 50, "pelagic targets", "King: 24 in fork length; Spanish: 12 in fork length.", "Legal offshore, not in pier buffer."),
    fish("Hogfish", "Outer reef sand patches", 92, 25, "trophy spear", "16 in fork length; 1/day; May 1-Oct 31.", "Closed Nov 1-Apr 30.")
  ]
};

const spotReports = {
  "lower-keys": {
    location: "Lower Keys, Florida",
    camera_image: "camera-snapshots/lower-keys.jpg?v=20260827-0301",
    live_url: "https://www.youtube.com/watch?v=qi0mY6zVQnY",
    live_embed_url: "https://www.youtube.com/embed/qi0mY6zVQnY?autoplay=1&mute=1&playsinline=1&controls=1&rel=0&modestbranding=1",
    live_label: "Live Lower Keys cam",
    grade: "B",
    score: 70,
    visibility: [15, 25],
    bestWindow: "Morning before wind texture",
    waveWeight: "Light to moderate",
    report: "Viz is currently sitting around 15-25 ft. The Lower Keys cam looks workable with clear patches through the water and some haze near structure. If wind stays light, this should be a solid reef day.\n\nHave fun out there divers :)",
    surf: 2.4,
    primary: [1.8, 10, "ESE", 116],
    secondary: [1.2, 7, "SE", 135],
    water: 80.6,
    wind: 8.2,
    fishContext: "Lower Keys reef target ranking",
    fishLegalLabel: "Spearfishing legal south of Long Key outside FKNMS no-take zones.",
    fishRuleLabel: "FWC take guidance",
    fishTargets: fishLists["lower-keys"],
  },
  "deerfield-beach": {
    location: "Deerfield Beach, Florida",
    camera_image: "camera-snapshots/deerfield-beach.jpg?v=20260827-0301",
    live_url: "https://www.youtube.com/watch?v=SHfAtWHr9Ks",
    live_embed_url: "https://www.youtube.com/embed/SHfAtWHr9Ks?autoplay=1&mute=1&playsinline=1&controls=1&rel=0&modestbranding=1",
    live_label: "Live Deerfield Beach cam",
    grade: "C",
    score: 58,
    visibility: [10, 18],
    bestWindow: "Early calm window",
    waveWeight: "Moderate",
    report: "Viz is currently sitting around 10-18 ft. The cam has some blue water but there is still enough texture and scatter to keep it from being clean-clean. Worth checking early if winds stay down.\n\nStay safe out there divers :)",
    surf: 3.0,
    primary: [2.2, 8, "E", 93],
    secondary: [1.1, 12, "NE", 48],
    water: 79.2,
    wind: 10.4,
    fishContext: "Broward pier + offshore reef target ranking",
    fishLegalLabel: "Cam is inside the 100-yard no-spear pier/beach buffer. Offshore reef tract rules are different.",
    fishRuleLabel: "FWC / pier-buffer guidance",
    fishTargets: fishLists["deerfield-beach"],
  },
  "utopia-sandy-channel": {
    location: "Utopia Village Sandy Channel, Roatan",
    camera_image: "camera-snapshots/utopia-sandy-channel.jpg?v=20260827-0301",
    live_url: "https://www.youtube.com/watch?v=jzx_n25g3kA",
    live_embed_url: "https://www.youtube.com/embed/jzx_n25g3kA?autoplay=1&mute=1&playsinline=1&controls=1&rel=0&modestbranding=1",
    live_label: "Live Sandy Channel cam",
    grade: "A",
    score: 84,
    visibility: [25, 35],
    bestWindow: "Most of the day",
    waveWeight: "Light",
    report: "Really solid visibility today, 25-35 ft. The sandy channel is showing bright water and clean contrast around the bottom. Slight haze at distance, but overall this is a go-dive setup.",
    surf: 1.7,
    primary: [1.1, 11, "E", 88],
    secondary: [0.8, 8, "ENE", 68],
    water: 82.1,
    wind: 6.0,
    fishContext: "Sandy-channel wildlife ranking",
    fishLegalLabel: "NO TAKE - Roatan Marine Park / BINMP. Lionfish is the only permit/workshop exception.",
    fishPrizeLabel: "Wow factor",
    fishRuleLabel: "Site guidance",
    fishTargets: fishLists["utopia-sandy-channel"],
  },
  "utopia-reef-cam": {
    location: "Utopia Village Reef Cam, Roatan",
    camera_image: "camera-snapshots/utopia-reef-cam.jpg?v=20260827-0301",
    live_url: "https://www.youtube.com/watch?v=nmjlQlYygB4",
    live_embed_url: "https://www.youtube.com/embed/nmjlQlYygB4?autoplay=1&mute=1&playsinline=1&controls=1&rel=0&modestbranding=1",
    live_label: "Live reef cam",
    grade: "A",
    score: 86,
    visibility: [25, 35],
    bestWindow: "Now through afternoon",
    waveWeight: "Light",
    report: "Viz is looking strong at 25-35 ft. The reef cam has clean water, good color, and enough detail on structure to call this a proper dive day. If you have the window, go get in.",
    surf: 1.5,
    primary: [1.0, 10, "E", 92],
    secondary: [0.7, 8, "NE", 54],
    water: 82.4,
    wind: 5.8,
    fishContext: "Roatan reef wildlife ranking",
    fishLegalLabel: "NO TAKE - Roatan Marine Park / BINMP. Lionfish is the only permit/workshop exception.",
    fishPrizeLabel: "Wow factor",
    fishRuleLabel: "Site guidance",
    fishTargets: fishLists["utopia-reef-cam"],
  },
  "catalina-wrigley": {
    location: "USC Wrigley Catalina Marine Reserve",
    camera_image: "camera-snapshots/catalina-wrigley.jpg?v=20260827-0301",
    live_url: "https://www.youtube.com/watch?v=JH_NzhSsqis",
    live_embed_url: "https://www.youtube.com/embed/JH_NzhSsqis?autoplay=1&mute=1&playsinline=1&controls=1&rel=0&modestbranding=1",
    live_label: "Live Catalina reserve cam",
    grade: "B",
    score: 72,
    visibility: [15, 25],
    bestWindow: "Calmer morning water",
    waveWeight: "Moderate",
    report: "Viz is sitting around 15-25 ft. Catalina looks diveable with good structure detail and some distance haze. Blue Cavern can clean up fast, so check the cam before splashing and keep it mellow in the MPA.",
    surf: 2.8,
    primary: [2.0, 15, "SSW", 205],
    secondary: [1.1, 8, "W", 277],
    water: 65.8,
    wind: 9.4,
    fishContext: "Catalina reserve wildlife ranking",
    fishLegalLabel: "NO TAKE - Blue Cavern Onshore SMCA / USC Wrigley reserve.",
    fishPrizeLabel: "Wow factor",
    fishRuleLabel: "Site guidance",
    fishTargets: fishLists["catalina-wrigley"],
  },
  "anacapa-ocean": {
    location: "Anacapa Ocean, Channel Islands",
    camera_image: "camera-snapshots/anacapa-ocean.jpg?v=20260827-0301",
    live_url: "https://www.youtube.com/watch?v=OAJF1Ie1m_Q",
    live_embed_url: "https://www.youtube.com/embed/OAJF1Ie1m_Q?autoplay=1&mute=1&playsinline=1&controls=1&rel=0&modestbranding=1",
    live_label: "Live Anacapa cam",
    grade: "C",
    score: 61,
    visibility: [10, 20],
    bestWindow: "Protected side if wind stays down",
    waveWeight: "Moderate",
    report: "Viz is currently sitting around 10-20 ft. Anacapa has some workable water but enough movement to keep the edges stirred. Pick protected water and do not force it if the surface gets bumpy.",
    surf: 3.2,
    primary: [2.4, 12, "W", 272],
    secondary: [1.4, 15, "SSW", 206],
    water: 63.4,
    wind: 11.0,
    fishContext: "Channel Islands kelp + pelagic ranking",
    fishLegalLabel: "ZONING VARIES - north-side SMR/SMCA restrictions; south side is open coast under CDFW rules.",
    fishRuleLabel: "CDFW zoning guidance",
    fishTargets: fishLists["anacapa-ocean"],
  },
  "coral-city": {
    location: "Coral City Camera, Miami",
    camera_image: "camera-snapshots/coral-city.jpg?v=20260827-0301",
    live_url: "https://www.youtube.com/watch?v=7i8ARjIeM2k",
    live_embed_url: "https://www.youtube.com/embed/7i8ARjIeM2k?autoplay=1&mute=1&playsinline=1&controls=1&rel=0&modestbranding=1",
    live_label: "Live Coral City cam",
    grade: "B",
    score: 74,
    visibility: [15, 25],
    bestWindow: "Bright midday water",
    waveWeight: "Light",
    report: "Viz is running around 15-25 ft on the reef cam. Water has good color and fish activity, with some city-water haze mixed in. Fun viewing conditions and a decent shallow reef read.",
    surf: 1.8,
    primary: [1.2, 9, "ESE", 112],
    secondary: [0.8, 6, "SE", 142],
    water: 81.0,
    wind: 7.4,
    fishContext: "PortMiami urban reef wildlife ranking",
    fishLegalLabel: "VIEWING ONLY - no diving, spearfishing, or fishing access at the camera site.",
    fishPrizeLabel: "Wow factor",
    fishRuleLabel: "Site guidance",
    fishTargets: fishLists["coral-city"],
  },
  "pompano-pier": {
    location: "Pompano Beach Underwater Pier Cam",
    camera_image: "camera-snapshots/pompano-pier.jpg?v=20260827-0301",
    live_url: "https://www.youtube.com/watch?v=mV8zVsX_o_0",
    live_embed_url: "https://www.youtube.com/embed/mV8zVsX_o_0?autoplay=1&mute=1&playsinline=1&controls=1&rel=0&modestbranding=1",
    live_label: "Live Pompano Beach pier cam",
    grade: "C",
    score: 59,
    visibility: [10, 18],
    bestWindow: "Before afternoon wind",
    waveWeight: "Moderate",
    report: "Viz is around 10-18 ft. The pier cam has fish and structure showing, but the water still has some suspended haze. Diveable if you are already nearby, better if wind stays mellow.",
    surf: 3.1,
    primary: [2.1, 8, "E", 91],
    secondary: [1.2, 11, "NE", 45],
    water: 79.5,
    wind: 10.2,
    fishContext: "Pompano pier + offshore reef target ranking",
    fishLegalLabel: "Cam is inside the 100-yard no-spear pier/beach buffer. Offshore reef tract rules are different.",
    fishRuleLabel: "FWC / pier-buffer guidance",
    fishTargets: fishLists["pompano-pier"],
  },
};

function buildChart(base, key) {
  return Array.from({ length: 24 }, (_, hour) => ({
    time: `${String(hour).padStart(2, "0")}:00`,
    [key]: Math.max(0.2, Number((base + Math.sin(hour / 3) * 0.35 + (hour > 13 && hour < 19 ? 0.4 : 0)).toFixed(2))),
  }));
}

function hydrateStaticSpotReport() {
  const slug = document.body.dataset.spot;
  const spot = spotReports[slug];
  if (!spot) return;

  document.title = `${spot.location} - DivePro`;
  const liveLink = document.querySelector(".camera-frame figcaption a");
  if (liveLink) {
    liveLink.href = spot.live_url;
    liveLink.textContent = spot.live_label;
  }

  window.staticSpotReport = {
    date: "2026-05-30",
    location: spot.location,
    camera_image: spot.camera_image,
    live_url: spot.live_url,
    live_embed_url: spot.live_embed_url,
    grade: spot.grade,
    numeric_score_0_100: spot.score,
    estimated_visibility_range_ft: spot.visibility,
    estimated_visibility_mid_ft: (spot.visibility[0] + spot.visibility[1]) / 2,
    best_window: spot.bestWindow,
    report_text: spot.report,
    fish_context: spot.fishContext,
    fish_legal_label: spot.fishLegalLabel,
    fish_prize_label: spot.fishPrizeLabel,
    fish_rule_label: spot.fishRuleLabel,
    fish_targets: spot.fishTargets,
    tide_source: "Local tide estimate",
    wind_source: "Hourly wind estimate",
    features: {
      surf_height_max_ft: spot.surf,
      wave_height_max_ft: spot.surf,
      swell_wave_height_max_ft: spot.primary[0],
      swell_wave_period_max_s: spot.primary[1],
      swell_direction_label: spot.primary[2],
      swell_wave_direction_deg: spot.primary[3],
      secondary_swell_height_ft: spot.secondary[0],
      secondary_swell_period_s: spot.secondary[1],
      secondary_swell_direction_label: spot.secondary[2],
      secondary_swell_direction_deg: spot.secondary[3],
      total_swell_height_mean_ft: spot.primary[0],
      wind_speed_max_mph: spot.wind,
      water_temp_estimate_f: spot.water,
      rain_target_day_forecast_in: 0,
      rain_prior_3day_in: 0,
      wind_chart: buildChart(spot.wind * 0.72, "speed_mph"),
      tide_chart: buildChart(2.1, "height_ft"),
    },
  };
}

hydrateStaticSpotReport();
